name: deploy
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    env:
      FORCE_CACHE_RESET: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Setup Node
        uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true' || env.FORCE_CACHE_RESET == 'true'
        with:
          node-version: lts/*
      - name: Npm Install
        if: steps.cache.outputs.cache-hit != 'true' || env.FORCE_CACHE_RESET == 'true'
        run: npm ci
  deploy:
    runs-on: ubuntu-latest
    needs: install-deps
    if: ${{ github.ref == 'refs/heads/master' }} # run only for master
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Build Project
        run: npx gatsby build
      - name: Deploy to Surge
        run: npx surge public/ --token ${{ secrets.SURGE_TOKEN }}
